CREATE TABLE korisnici (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ime VARCHAR(20) NOT NULL,
    prezime VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    korisnicko_ime VARCHAR(50) NOT NULL UNIQUE,
    lozinka VARCHAR(50) NOT NULL
);
SELECT * FROM korisnici;
DROP TABLE korisnici;

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE users;